# Generated by Django 5.2.4 on 2025-07-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
